### PR TITLE
docs: Add ADR for Python fm-training-estimator

### PR DESCRIPTION
**Pull request by aluu317**
Defines an ADR (Architecture Decision Record) for exposing fm-training-estimator as a Python library and high level design of input and output types to the main 4 functions the library will provide

### CODE REVIEW

**Review by ChanderG — COMMENTED** [review]
LGTM.

**Comment by aluu317** [comment]
@ChanderG I don't have write access to merge. Please merge when you get a chance

**Comment by praveenj83** [comment]
I gave you access, @aluu317. Can you please try now? I need to figure out the groups and allow our full team access, but at least you should have access now.

**Comment by aluu317** [comment]
@praveenj83 It still says `Only those with write access to this repository can merge pull requests.` for me

**Pull request merged**
